/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.4.1/userguide/tutorial_java_projects.html
 */

plugins {
    // Apply the java plugin to add support for Java
    java

    // Apply the application plugin to add support for building an application
    application

    // Support for generating parsers using ANTLR.
    antlr
}

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    antlr("org.antlr:antlr4:4.7.2")
}

application {
    // Define the main class for the application
    mainClassName = "it.albmoriconi.mal.Assembler"
}

tasks.generateGrammarSource {
    arguments = arguments + listOf("-package", "it.albmoriconi.mal.antlr")
}